cloud:
  aws:
    credentials:
      access-key: access - key
      secret-key: seceret - key
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/237142071300/newsqs.fifo
    region:
      auto: false
      static: us-east-1
    stack:
      auto: false
server:
    port: 9003
